### ISSUE TITLE
cannot import name 'Dataset' from 'datasets'

### ISSUE THREAD

**Issue by hmsklv0** [zealscott/SynMeter#3]
我在使用`python3 scripts/tune_synthesizer.py -d adult -m great`遇到了问题
```sh
(synmeter) [root@localhost SynMeter]# python3 scripts/tune_synthesizer.py -d adult -m great
Traceback (most recent call last):
  File "/root/bishe/42synmeter/SynMeter/scripts/tune_synthesizer.py", line 66, in <module>
    main()
  File "/root/bishe/42synmeter/SynMeter/scripts/tune_synthesizer.py", line 54, in main
    synthesizer = __import__("synthesizer." + args.model, fromlist=[args.model])
  File "/root/bishe/42synmeter/SynMeter/synthesizer/great.py", line 2, in <module>
    from .be_great import GReaT
  File "/root/bishe/42synmeter/SynMeter/synthesizer/be_great/__init__.py", line 1, in <module>
    from .great import GReaT
  File "/root/bishe/42synmeter/SynMeter/synthesizer/be_great/great.py", line 15, in <module>
    from .great_dataset import GReaTDataset, GReaTDataCollator
  File "/root/bishe/42synmeter/SynMeter/synthesizer/be_great/great_dataset.py", line 4, in <module>
    from datasets import Dataset
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)
```

**Comment by yuntaod** [comment]
Hi @hmsklv0,

Thanks for using SynMeter~ `datasets` is a Python package, you can install with: `pip install datasets`.
